### ISSUE TITLE
M5atom-lite

### ISSUE THREAD

**Issue by gutowscr471** [Sleeper85/esphome-jk-bms-can#11]
Had issues with the latest configuration files for wired. Think you need to update to type: arduino or mention it in the comments for wired.

config/config_atom-lite-esp32-pico.yaml

 esp32:
  board: m5stack-atom
  framework:
    type: arduino

**Comment by Sleeper85** [comment]
Noted. I will ask the person responsible for this platform to do some testing.

**Comment by Sleeper85** [comment]
According to my research Atom Lite works well with the **esp-idf** framework.

What error do you receive exactly when compiling the YAML?

**Comment by Sleeper85** [comment]
It actually seems that it is difficult to compile the YAML with Atom Lite (esp32-pico) and **esp-idf**.
Additionally Atom Lite is not stable with the BLE version. I changed to **arduino**.

Thanks
