### ISSUE TITLE
RS485 Pylon support

### ISSUE THREAD

**Issue by lucize** [Sleeper85/esphome-jk-bms-can#18]
so with this pull request https://github.com/esphome/esphome/pull/4874, esphome can act as a slave
I think there are already implementation on r485 pylon monitoring via modbus, shouldn't be this easy to just expose those registers to the modbus server part and use li-ion protocol 12 on deye inverter ?
I ask about this because at the moment I don't understand what happened to my CAN setup it seems I can't make it work again, but I see that rs485 mode is asking data from the bms.
can it be that my can part to be faulty, or just the mcp2515 maybe got faulty ?

**Comment by Sleeper85** [comment]
Hi,

Regarding your problem with CAN, I don't know.
This project only supports CAN bus and I have no plans to add RS485 communication.
