### ISSUE TITLE
Current control oscillation

### ISSUE THREAD

**Issue by luckylinux** [Sleeper85/esphome-jk-bms-can#34]
![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/5a9048c5-0c95-416c-a0e5-fb750af4c2bc)

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/3427e3fa-13cc-4ff2-a6f1-ca812d931848)

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/04905015-f105-4a61-90b8-18a8e1927993)

OVPR is set at 3.52 VDC:
![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/01acb809-c42e-46b9-bd89-67b91841418e)

Detail of max cell voltage
![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/1c77284a-e31d-4029-8343-1d54818d7219)

**Comment by luckylinux** [comment]
Sure, I removed the overvoltage protection from the plots that are for single cells (much lower of course)

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/65478a3f-2b69-4de8-b126-12759fe7fdc2)

**Comment by MrPabloUK** [comment]
So at the time of the current oscillation, your float voltage was 56.1v, or 3.506v per cell?

**Comment by luckylinux** [comment]
> So at the time of the current oscillation, your float voltage was 56.1v, or 3.506v per cell?

Yeah, I needed to raise it because otherwise it will never balance out ...

**Comment by MrPabloUK** [comment]
With the following settings:
- Float = 3.506v
- OVPR = 3.520v
- End of Curve Factor = 2.0
- Curve Shape = 0.4
- Max Charge Current = 180A

You end up with a curve like this:
![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/47826763/3db75c83-e8cf-429a-aac7-92ddc4aa3e76)

Those settings result in a request to reduce current 180A over 14mV. That's not realistic, even if it were linear then it'd be nearly 13A per mV.

You should set float back to 3.37v or so, expanding the range over which the current will be reduced.
I know you've had issues keeping the charge state in bulk or balancing - my suggestion is to lower the balance trigger voltage to below 3.45v as previously stated.
The changes mentioned in https://github.com/Sleeper85/esphome-jk-bms-can/issues/35 may also help.

**Comment by luckylinux** [comment]
But if I recalled correctly, previously (yesterday ?), this was also happening during Bulk, not only Float ...

**Comment by MrPabloUK** [comment]
The code for this feature uses the cell float voltage as the start point of current tapering.
This is why I suggest setting your float voltage back to a more reasonable setting. Artificially increasing the float voltage in order to facilitate balancing shouldn't be necessary, assuming the balance trigger voltage is appropriately set.

**Comment by luckylinux** [comment]
I agree. Problem is that even though I properly balanced it 3 weeks ago, it unbalanced quite quickly since then (and I don't think I went above the required knee point of the charge characteristic, when there was no communication between Inverter and BMS).

**Comment by MrPabloUK** [comment]
For now, I'll close this issue out as the code itself is not causing the problem.
Thanks for testing out an edge case!
