### ISSUE TITLE
Premature triggering of EOC

### ISSUE THREAD

**Issue by luckylinux** [Sleeper85/esphome-jk-bms-can#35]
Please note that Balancing is ON yet the ESP32 went into FLOAT charging status now.

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/e66700c1-8a24-426c-95aa-c133e183b714)

Probably this happens because for a second or so (probably battery discharged for a few seconds) the cell voltage went below balance trigger voltage, due to the battery being discharged (either because of clouds or load step):
![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/66d764d3-8bbe-4792-96ca-859e497597bd)

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/572900e2-b20b-45d1-9e9e-93d8fc867a78)

**Comment by MrPabloUK** [comment]
@luckylinux, I have been testing a cycle / time threshold for triggering EOC, you can see the change to the code at https://github.com/Sleeper85/esphome-jk-bms-can/commit/d4f257c0c6f2087cd41c3afcfed662160467edf6

Please note that this is currently a 60 cycle threshold and this section of code is generally run once per second.
This will not prevent EOC from being triggered if current reduction is due to generation or load changes if they last for more than this time.

**Comment by MrPabloUK** [comment]
Please note that this logic is liable to change in the future packaged version under development.

**Comment by MrPabloUK** [comment]
You can see it in https://github.com/Sleeper85/esphome-jk-bms-can/compare/35-premature-triggering-of-eoc, applied to a single YAML for now.

If you can test the code first with the default 60 cycles, that would be appreciated.
If required, you can then manually adjust this value - future code versions will likely have it as a parameter for user adjustment.

I would caution against a period as long as 30 minutes however, that will likely overcharge your cells as per the detail in https://nordkyndesign.com/charging-marine-lithium-battery-banks/.

**Comment by luckylinux** [comment]
OK so basically backport the "delta" into my version, got it.

What do you mean by "overcharge your cells" ? Isn't that how top balance works anyways ? And as long as all cells < 3.65 VDC it shouldn't overcharge ...

**Comment by luckylinux** [comment]
@MrPabloUK: What would happen if now, I disable BLE connection from ESP32 to JK BMS (concerning CAN Communication) ? Would it cause the inverter to trip (BMS_Err_Stop is SET now).

**Comment by MrPabloUK** [comment]
Honestly, I don't know for certain. I use a wired connection as I don't quite trust BLE for this project.
The change made in the previously mentioned branch may be released in the next sub-release, once it's been tidied up.

**Comment by luckylinux** [comment]
Question is ... If I were to implement multi BMS like Der_Hannes did, should I use this as a base or the development branch ?

**Comment by MrPabloUK** [comment]
Closing issue as feature has been added to V1.17.5
