### ISSUE TITLE
Multiple BMS and thus CAN addresses

### ISSUE THREAD

**Issue by Maikel-K** [Sleeper85/esphome-jk-bms-can#45]
Hi,

I have 9 JK-BMSes, would it be possible with your code to give each ESP a different CAN bus address and connected them all to 1 Victron Cerbo GX (RPI with VenusOS running)

**Comment by Sleeper85** [comment]
Hi,

Not today. Multi-bms on can bus with slaves and a master is a solution that will be developed in the future.
Yesterday I posted a first multi-BMS code in the development branch but all the BMS must be connected to the same board. With the PVbrain2 card and an ESP32-S3 it would be possible to connect 12 bms.
