### ISSUE TITLE
[Solved] (logger DEBUG) - Balance is reported as ON while actually being OFF

### ISSUE THREAD

**Issue by virus100b** [Sleeper85/esphome-jk-bms-can#49]
Hello. The problem i have is that sometimes is reporting balance ON when actually balance is OFF, checked by connecting to the BMS over bluetooth. If i restart the ESP the Balance reporting is showing correct state. I don't know why is doing that.

ESP Home - Balancing reported as ON.
![WhatsApp Image 2024-05-15 at 21 38 43](https://github.com/Sleeper85/esphome-jk-bms-can/assets/64686560/0752f0ca-b91c-4d42-887b-1bb641a2dc17)

JK BT app. Balancing is OFF.
![WhatsApp Image 2024-05-15 at 21 38 54](https://github.com/Sleeper85/esphome-jk-bms-can/assets/64686560/71fc0ac3-cbbc-4e46-a0db-28acc0f590bf)

**Comment by virus100b** [comment]
Same behavior related to Charging Switch.

ESP Home Charging switch reported as Off.
![WhatsApp Image 2024-05-15 at 21 53 32](https://github.com/Sleeper85/esphome-jk-bms-can/assets/64686560/295783dc-14e3-4e8b-a5d9-7f433700d9d6)

BMS App - Charging is ON
![WhatsApp Image 2024-05-15 at 21 53 26](https://github.com/Sleeper85/esphome-jk-bms-can/assets/64686560/2dd0c4fe-4a5b-4f9a-85db-b1b377cfc421)

**Comment by Sleeper85** [comment]
Several people including @MrPabloUK have reported a problem refreshing data received when logger is on INFO. This problem does not occur with logger on DEBUG. We don't know if this is related to a certain version of HA, esphome or syssi components, this still needs to be verified.
Please change your config and stay with DEBUG in production.

```YAML
logger:
  level: DEBUG
```

**Comment by virus100b** [comment]
I will change that and monitor. Thank you !

**Comment by virus100b** [comment]
I have modified logger to DEBUG and now is working fine. 
Thank you for help!
