### ISSUE TITLE
Instruction=Status=Bulk

### ISSUE THREAD

**Issue by txubelaxu** [Sleeper85/esphome-jk-bms-can#56]
In my opinion, when **Instruction** is **Bulk**, but the **I=0A**, then the status should be "**Idle**" (or something like that)

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/156140720/e3ad3ffb-443a-450e-9350-3739060987ce)

**Comment by Sleeper85** [comment]
Hi,

I have seen your messages as well as the PR. I'm currently busy with another project. I'll look into it and get back to you soon.

**Comment by shvmm** [comment]
Current being 0 while in **Bulk** represents a specific situation/mitigation in the charging logic loop.
What were the exact conditions that caused this to happen?

Adding a status named Idle is easy but the charging logic depends on the specific states to communicate values to the inverter.

**Comment by txubelaxu** [comment]
OK. I undestand.

The conditions were: 2xBMS in a stationary status and no inverter conected
to the system.

Many thanks for the info!!

**Comment by Sleeper85** [comment]
As @shvmm says the only way to exit a Bulk phase is for it to end with a fully charged battery, no matter if the current is zero, negative or positive.
