### ISSUE TITLE
Slider Charging current max

### ISSUE THREAD

**Issue by oseldusan** [Sleeper85/esphome-jk-bms-can#6]
Hi Sleeper85.
Could you please correct row No. 1005 in your yaml , where is max value for slider Charging current max right now 150A? I suggest to use max_value: "${charge_a}"   . Thank you very much.

**Comment by Sleeper85** [comment]
Hi oseldusan,
If we define it with the value of ${charge_a} then we cannot increase it via the slider. I don't know if this is a good idea, would that mean that ${charge_a} is the max value?

**Comment by pgwg-uk** [comment]
You can set the slider to have an initial value, inherited from charge_a:

    initial_value: "${charge_a}"

If restore_value is set to true, any changes will be kept during a reboot.

**Comment by OselDusan7** [comment]
Thats correct. So what about bigger value ? 200A ? 300A ? 2x${charge_a}, ${charge_a} +50A  , new value which can be set at "user area" at begining ? I know , I can change it by myself in code , but after few days ( weeks ) I have no idea what I did in the past :o) , and I will replace it with your new code.

**Comment by Sleeper85** [comment]
Ok, using ${charge_a} +50A seems like a good idea.

**Comment by Sleeper85** [comment]
Adapted in V1.16.1.
